language: java
jdk:
  - oraclejdk8
before_install:
- pip install --user codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
  -codecov
cache:
  directories:
    - '$HOME/.m2/repository'