exports.NATIONAL = [
    {country:"Andorra"},
    {country:"De forente arabiske emirater"},
    {country:"Afghanistan"},
    {country:"Antigua og Barbuda"},
    {country:"Anguilla"},
    {country:"Albania"},
    {country:"Armenia"},
    {country:"De nederlandske antiller"},
    {country:"Angola"},
    {country:"Antarktis"},
    {country:"Argentina"},
    {country:"Amerikansk Samoa"},
    {country:"Østerrike"},
    {country:"Australia"},
    {country:"Aruba"},
    {country:"Åland"},
    {country:"Aserbajdsjan"},
    {country:"Bosnia-Hercegovina"},
    {country:"Barbados"},
    {country:"Bangladesh"},
    {country:"Belgia"},
    {country:"Burkina Faso"},
    {country:"Bulgaria"},
    {country:"Bahrain"},
    {country:"Burundi"},
    {country:"Benin"},
    {country:"Saint-Barthélemy"},
    {country:"Bermuda"},
    {country:"Brunei"},
    {country:"Bolivia"},
    {country:"Brasil"},
    {country:"Bahamas"},
    {country:"Bhutan"},
    {country:"Bouvetøya"},
    {country:"Botswana"},
    {country:"Hviterussland"},
    {country:"Belize"},
    {country:"Canada"},
    {country:"Kokosøyene"},
    {country:"Kongo"},
    {country:"Den sentralafrikanske republikk"},
    {country:"Kongo-Brazzaville"},
    {country:"Sveits"},
    {country:"Elfenbenskysten"},
    {country:"Cookøyene"},
    {country:"Chile"},
    {country:"Kamerun"},
    {country:"Kina"},
    {country:"Colombia"},
    {country:"Costa Rica"},
    {country:"Cuba"},
    {country:"Kapp Verde"},
    {country:"Christmasøya"},
    {country:"Kypros"},
    {country:"Tsjekkia"},
    {country:"Tyskland"},
    {country:"Djibouti"},
    {country:"Danmark"},
    {country:"Dominica"},
    {country:"Den dominikanske republikk"},
    {country:"Algerie"},
    {country:"Ecuador"},
    {country:"Estland"},
    {country:"Egypt"},
    {country:"Vest-Sahara"},
    {country:"Eritrea"},
    {country:"Spania"},
    {country:"Etiopia"},
    {country:"Finland"},
    {country:"Fiji"},
    {country:"Falklandsøyene"},
    {country:"Mikronesiaføderasjonen"},
    {country:"Færøyene"},
    {country:"Frankrike"},
    {country:"Gabon"},
    {country:"Storbritannia"},
    {country:"Grenada"},
    {country:"Georgia"},
    {country:"Fransk Guyana"},
    {country:"Guernsey"},
    {country:"Ghana"},
    {country:"Gibraltar"},
    {country:"Grønland"},
    {country:"Gambia"},
    {country:"Guinea"},
    {country:"Guadeloupe"},
    {country:"Ekvatorial-Guinea"},
    {country:"Hellas"},
    {country:"Sør-Georgia og de søre Sandwichøyene"},
    {country:"Guatemala"},
    {country:"Guam"},
    {country:"Guinea-Bissau"},
    {country:"Guyana"},
    {country:"Hongkong"},
    {country:"Heard- og McDonald-øyene"},
    {country:"Honduras"},
    {country:"Kroatia"},
    {country:"Haiti"},
    {country:"Ungarn"},
    {country:"Indonesia"},
    {country:"Irland"},
    {country:"Israel"},
    {country:"Man"},
    {country:"India"},
    {country:"Britisk territorium i Indiahavet"},
    {country:"Irak"},
    {country:"Iran"},
    {country:"Island"},
    {country:"Italia"},
    {country:"Jersey"},
    {country:"Jamaica"},
    {country:"Jordan"},
    {country:"Japan"},
    {country:"Kenya"},
    {country:"Kirgisistan"},
    {country:"Kambodsja"},
    {country:"Kiribati"},
    {country:"Komorene"},
    {country:"Saint Kitts og Nevis"},
    {country:"Nord-Korea"},
    {country:"Sør-Korea"},
    {country:"Kuwait"},
    {country:"Caymanøyene"},
    {country:"Kasakhstan"},
    {country:"Laos"},
    {country:"Libanon"},
    {country:"Saint Lucia"},
    {country:"Liechtenstein"},
    {country:"Sri Lanka"},
    {country:"Liberia"},
    {country:"Lesotho"},
    {country:"Litauen"},
    {country:"Luxembourg"},
    {country:"Latvia"},
    {country:"Libya"},
    {country:"Marokko"},
    {country:"Monaco"},
    {country:"Moldova"},
    {country:"Montenegro"},
    {country:"Saint-Martin"},
    {country:"Madagaskar"},
    {country:"Marshalløyene"},
    {country:"Makedonia"},
    {country:"Mali"},
    {country:"Burma"},
    {country:"Mongolia"},
    {country:"Macao"},
    {country:"Nord-Marianene"},
    {country:"Martinique"},
    {country:"Mauritania"},
    {country:"Montserrat"},
    {country:"Malta"},
    {country:"Mauritius"},
    {country:"Maldivene"},
    {country:"Malawi"},
    {country:"Mexico"},
    {country:"Malaysia"},
    {country:"Mosambik"},
    {country:"Namibia"},
    {country:"Ny-Caledonia"},
    {country:"Niger"},
    {country:"Norfolk Island"},
    {country:"Nigeria"},
    {country:"Nicaragua"},
    {country:"Nederland"},
    {country:"Norge"},
    {country:"Nepal"},
    {country:"Nauru"},
    {country:"Niue"},
    {country:"New Zealand"},
    {country:"Oman"},
    {country:"Panama"},
    {country:"Peru"},
    {country:"Fransk Polynesia"},
    {country:"Papua Ny-Guinea"},
    {country:"Filippinene"},
    {country:"Pakistan"},
    {country:"Polen"},
    {country:"Saint-Pierre-et-Miquelon"},
    {country:"Pitcairn"},
    {country:"Puerto Rico"},
    {country:"De okkuperte palestinske områdene"},
    {country:"Portugal"},
    {country:"Palau"},
    {country:"Paraguay"},
    {country:"Qatar"},
    {country:"Réunion"},
    {country:"Romania"},
    {country:"Serbia"},
    {country:"Russland"},
    {country:"Rwanda"},
    {country:"Saudi-Arabia"},
    {country:"Salomonøyene"},
    {country:"Seychellene"},
    {country:"Sudan"},
    {country:"Sverige"},
    {country:"Singapore"},
    {country:"St. Helena"},
    {country:"Slovenia"},
    {country:"Svalbard og Jan Mayen"},
    {country:"Slovakia"},
    {country:"Sierra Leone"},
    {country:"San Marino"},
    {country:"Senegal"},
    {country:"Somalia"},
    {country:"Surinam"},
    {country:"São Tomé og Príncipe"},
    {country:"El Salvador"},
    {country:"Syria"},
    {country:"Swaziland"},
    {country:"Turks- og Caicosøyene"},
    {country:"Tsjad"},
    {country:"Søre franske territorier"},
    {country:"Togo"},
    {country:"Thailand"},
    {country:"Tadsjikistan"},
    {country:"Tokelau"},
    {country:"Øst-Timor"},
    {country:"Turkmenistan"},
    {country:"Tunisia"},
    {country:"Tonga"},
    {country:"Tyrkia"},
    {country:"Trinidad og Tobago"},
    {country:"Tuvalu"},
    {country:"Taiwan"},
    {country:"Tanzania"},
    {country:"Ukraina"},
    {country:"Uganda"},
    {country:"USA, mindre, utenforliggende øyer"},
    {country:"USA"},
    {country:"Uruguay"},
    {country:"Usbekistan"},
    {country:"Vatikanstaten"},
    {country:"Saint Vincent og Grenadinene"},
    {country:"Venezuela"},
    {country:"Jomfruøyene (Britisk)"},
    {country:"Jomfruøyene (USA)"},
    {country:"Vietnam"},
    {country:"Vanuatu"},
    {country:"Wallis- og Futunaøyene"},
    {country:"Samoa"},
    {country:"Jemen"},
    {country:"Mayotte"},
    {country:"Sør-Afrika"},
    {country:"Zambia"},
    {country:"Zimbabwe"}
];