package digitalcitizen.controllers;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.fakemongo.Fongo;
import com.google.gson.Gson;
import com.mongodb.*;
import com.mongodb.util.JSON;
import digitalcitizen.Application;
import digitalcitizen.models.Submission;
import digitalcitizen.repositories.SubmissionRepository;
import digitalcitizen.utilities.PDFManager;
import digitalcitizen.utilities.SubmissionValidator;

import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;


@RestController
public class SubmitController {

    private DB db = new Fongo("mongo server 1").getDB("digitalcitizen");
    private DBCollection collection = db.getCollection("submissions");

    @Autowired
    private SubmissionRepository submissionRepository;

    /**
     * This method receives and handles applications submitted on the route "/send".
     *
     * @param submission An application in JSON format. Converted to {@link Submission} by Spring.
     * @param request    HTTP request sent by the user. Containing client information.
     * @return A submission identification used in {@link #getPDF(String)} to generate a PDF.
     * @throws IOException
     */
    @CrossOrigin
    @RequestMapping(value = "/send", method = RequestMethod.POST)
    public
    @ResponseBody
    String post(@RequestBody final Submission submission, HttpServletRequest request) throws IOException {

        // Validate form
        printSubmissionRequest(submission, request);
        boolean submissionIsValid = new SubmissionValidator().validateAllFields(submission);

        // TODO: Add logic for handling disapproved submissions
        /*
        if(!submissionIsValid) {
            return "";
        }*/

        if (Application.USE_MONGODB) {
            // Add submission to database and return the id
            return submissionRepository.insert(handleSubmissionFields(submission)).getId();
        } else {
            //Converting Submission to BasicDBObject
            Gson gson = new Gson();
            BasicDBObject obj = (BasicDBObject) JSON.parse(gson.toJson(handleSubmissionFields(submission)));

            // Insert record and retrieve generated id
            collection.insert(obj);
            ObjectId submissionId = (ObjectId) obj.get("_id");

            // Return the id of the Submission
            return submissionId.toString();
        }
    }

    /**
     * A method that handles the individual fields of the application.
     * This includes looking up and updating person data, based upon the
     * information given, such as pnr, name and address.
     *
     * @param submission The {@link Submission} to be reviewed.
     * @return The updated {@link Submission}
     */
    private Submission handleSubmissionFields(Submission submission) {
        if (submission.getPerson().getPnr() != null && !submission.getPerson().getPnr().equals("")) {
            submission.getPerson().updateValuesByPnr();
        }
        return submission;
    }

    /**
     * Generates and returns a PDF of a submitted application when request on the route
     * /getpdf with an "id" parameter (Generated by {@link #post(Submission, HttpServletRequest)}.
     *
     * @param id The id of the submission we want to generate a PDF-file from.
     * @return HTTP containing the generated PDF-file
     * @throws IOException
     */
    @CrossOrigin
    @RequestMapping(value = "/getpdf", params = "id", method = RequestMethod.GET)
    public ResponseEntity<byte[]> getPDF(@RequestParam("id") String id) throws IOException {

        Submission submission;
        if (Application.USE_MONGODB) {
            // Get Submission from database by the provided id
            submission = submissionRepository.findById(id);
        } else {
            // Retrieve Submission JSON from database by the provided ID
            DBObject searchById = new BasicDBObject("_id", new ObjectId(id));
            DBObject found = collection.findOne(searchById);

            // Convert JSON to an instance of Submission
            ObjectMapper mapper = new ObjectMapper().disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
            submission = mapper.readValue(found.toString(), Submission.class);
        }

        // Generate PDF of the submission
        PDFManager pdfManager = new PDFManager();
        Path path = Paths.get(pdfManager.generatePDFofSubmission(submission));
        byte[] contents = Files.readAllBytes(path);

        // Add required headers and metadata
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.parseMediaType("application/pdf"));
        String filename = "Søknad.pdf";
        headers.setContentDispositionFormData(filename, filename);
        headers.setCacheControl("must-revalidate, post-check=0, pre-check=0");

        // TODO: Authenticate the user before sending the PDF-file
        return new ResponseEntity<>(contents, headers, HttpStatus.OK);
    }

    private void printSubmissionRequest(Submission submission, HttpServletRequest request) {
        String s = "Submission received from: " + request.getRemoteAddr()
                + '\n' + submission;
        System.out.println(s);
    }
}


